// <auto-generated />
namespace mvc_shop_data_access_sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedorders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedorders));
        
        string IMigrationMetadata.Id
        {
            get { return "202106010644292_Addedorders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
